"""Fixture tracks so the product feels alive without API credentials."""

from __future__ import annotations

from typing import Any, Dict, List

from app.services.matching_engine import TrackRef
from app.services.recommender import AudioTrack


DEMO_PLAYLISTS: List[Dict[str, Any]] = [
    {
        "id": "demo-chill-vibes",
        "name": "Chill Vibes",
        "platform": "spotify",
        "track_count": 8,
        "description": "Late-night wind-down energy",
    },
    {
        "id": "demo-workout-fire",
        "name": "Workout Fire",
        "platform": "spotify",
        "track_count": 8,
        "description": "Peak BPM pump-up",
    },
    {
        "id": "demo-sunday-drive",
        "name": "Sunday Drive",
        "platform": "apple",
        "track_count": 8,
        "description": "Open-road feel-good mix",
    },
]


def demo_spotify_tracks() -> List[Dict[str, Any]]:
    return [
        {
            "id": "sp-1",
            "title": "Blinding Lights",
            "artist": "The Weeknd",
            "album": "After Hours",
            "isrc": "USUG11904206",
            "danceability": 0.51,
            "energy": 0.80,
            "valence": 0.35,
            "tempo": 171.0,
            "acousticness": 0.001,
            "key": 1,
            "mode": 1,
            "duration_ms": 200040,
        },
        {
            "id": "sp-2",
            "title": "Levitating",
            "artist": "Dua Lipa",
            "album": "Future Nostalgia",
            "isrc": "GBAHT1901298",
            "danceability": 0.70,
            "energy": 0.82,
            "valence": 0.92,
            "tempo": 103.0,
            "acousticness": 0.01,
            "key": 6,
            "mode": 0,
            "duration_ms": 203064,
        },
        {
            "id": "sp-3",
            "title": "As It Was",
            "artist": "Harry Styles",
            "album": "Harry's House",
            "isrc": "USSM12200612",
            "danceability": 0.52,
            "energy": 0.73,
            "valence": 0.66,
            "tempo": 174.0,
            "acousticness": 0.34,
            "key": 7,
            "mode": 1,
            "duration_ms": 167303,
        },
        {
            "id": "sp-4",
            "title": "Stay",
            "artist": "The Kid LAROI & Justin Bieber",
            "album": "F*CK LOVE 3",
            "isrc": "USSM12100501",
            "danceability": 0.59,
            "energy": 0.76,
            "valence": 0.48,
            "tempo": 170.0,
            "acousticness": 0.04,
            "key": 1,
            "mode": 1,
            "duration_ms": 141806,
        },
        {
            "id": "sp-5",
            "title": "good 4 u",
            "artist": "Olivia Rodrigo",
            "album": "SOUR",
            "isrc": "USUG12101838",
            "danceability": 0.56,
            "energy": 0.90,
            "valence": 0.68,
            "tempo": 167.0,
            "acousticness": 0.01,
            "key": 9,
            "mode": 1,
            "duration_ms": 178147,
        },
        {
            "id": "sp-6",
            "title": "Heat Waves",
            "artist": "Glass Animals",
            "album": "Dreamland",
            "isrc": "GBUM72000433",
            "danceability": 0.76,
            "energy": 0.53,
            "valence": 0.53,
            "tempo": 81.0,
            "acousticness": 0.44,
            "key": 11,
            "mode": 1,
            "duration_ms": 238805,
        },
        {
            "id": "sp-7",
            "title": "Save Your Tears",
            "artist": "The Weeknd",
            "album": "After Hours",
            "isrc": "USUG11904207",
            "danceability": 0.68,
            "energy": 0.82,
            "valence": 0.59,
            "tempo": 118.0,
            "acousticness": 0.02,
            "key": 0,
            "mode": 1,
            "duration_ms": 215627,
        },
        {
            "id": "sp-8",
            "title": "Peaches",
            "artist": "Justin Bieber",
            "album": "Justice",
            "isrc": "USUM72102635",
            "danceability": 0.68,
            "energy": 0.70,
            "valence": 0.46,
            "tempo": 90.0,
            "acousticness": 0.32,
            "key": 0,
            "mode": 1,
            "duration_ms": 198082,
        },
    ]


def demo_apple_tracks() -> List[Dict[str, Any]]:
    """Overlapping catalog with some ISRC matches and some fuzzy-only."""
    return [
        {
            "id": "am-1",
            "title": "Blinding Lights",
            "artist": "The Weeknd",
            "album": "After Hours",
            "isrc": "USUG11904206",
            "danceability": 0.51,
            "energy": 0.80,
            "valence": 0.35,
            "tempo": 171.0,
            "acousticness": 0.001,
            "key": 1,
            "mode": 1,
        },
        {
            "id": "am-2",
            "title": "Levitating (feat. DaBaby)",
            "artist": "Dua Lipa",
            "album": "Future Nostalgia",
            "isrc": "GBAHT1901298",
            "danceability": 0.70,
            "energy": 0.82,
            "valence": 0.92,
            "tempo": 103.0,
            "acousticness": 0.01,
            "key": 6,
            "mode": 0,
        },
        {
            "id": "am-3",
            "title": "As It Was",
            "artist": "Harry Styles",
            "album": "Harry's House",
            "isrc": "USSM12200612",
            "danceability": 0.52,
            "energy": 0.73,
            "valence": 0.66,
            "tempo": 174.0,
            "acousticness": 0.34,
            "key": 7,
            "mode": 1,
        },
        # Fuzzy-only (slightly different title / no ISRC on one side)
        {
            "id": "am-4",
            "title": "Stay",
            "artist": "The Kid LAROI",
            "album": "F*CK LOVE 3: OVER YOU",
            "isrc": None,
            "danceability": 0.59,
            "energy": 0.76,
            "valence": 0.48,
            "tempo": 170.0,
            "acousticness": 0.04,
            "key": 1,
            "mode": 1,
        },
        {
            "id": "am-5",
            "title": "good 4 u",
            "artist": "Olivia Rodrigo",
            "album": "SOUR",
            "isrc": "USUG12101838",
            "danceability": 0.56,
            "energy": 0.90,
            "valence": 0.68,
            "tempo": 167.0,
            "acousticness": 0.01,
            "key": 9,
            "mode": 1,
        },
        {
            "id": "am-6",
            "title": "Heat Waves",
            "artist": "Glass Animals",
            "album": "Dreamland",
            "isrc": "GBUM72000433",
            "danceability": 0.76,
            "energy": 0.53,
            "valence": 0.53,
            "tempo": 81.0,
            "acousticness": 0.44,
            "key": 11,
            "mode": 1,
        },
        # Apple-only tracks for richer catalog / recommendations
        {
            "id": "am-7",
            "title": "drivers license",
            "artist": "Olivia Rodrigo",
            "album": "SOUR",
            "isrc": "USUG12004700",
            "danceability": 0.56,
            "energy": 0.43,
            "valence": 0.14,
            "tempo": 144.0,
            "acousticness": 0.76,
            "key": 10,
            "mode": 1,
        },
        {
            "id": "am-8",
            "title": "Watermelon Sugar",
            "artist": "Harry Styles",
            "album": "Fine Line",
            "isrc": "USSM11912588",
            "danceability": 0.55,
            "energy": 0.82,
            "valence": 0.56,
            "tempo": 95.0,
            "acousticness": 0.12,
            "key": 0,
            "mode": 1,
        },
        {
            "id": "am-9",
            "title": "Don't Start Now",
            "artist": "Dua Lipa",
            "album": "Future Nostalgia",
            "isrc": "GBAHT1901122",
            "danceability": 0.79,
            "energy": 0.79,
            "valence": 0.68,
            "tempo": 124.0,
            "acousticness": 0.01,
            "key": 11,
            "mode": 0,
        },
        {
            "id": "am-10",
            "title": "Circles",
            "artist": "Post Malone",
            "album": "Hollywood's Bleeding",
            "isrc": "USUM71916164",
            "danceability": 0.70,
            "energy": 0.76,
            "valence": 0.55,
            "tempo": 120.0,
            "acousticness": 0.23,
            "key": 0,
            "mode": 1,
        },
    ]


def as_track_refs(rows: List[Dict[str, Any]], platform: str) -> List[TrackRef]:
    return [
        TrackRef(
            id=r["id"],
            title=r["title"],
            artist=r["artist"],
            platform=platform,
            isrc=r.get("isrc"),
            album=r.get("album"),
            extras={k: v for k, v in r.items() if k not in ("id", "title", "artist", "isrc", "album")},
        )
        for r in rows
    ]


def as_audio_tracks(rows: List[Dict[str, Any]]) -> List[AudioTrack]:
    return [
        AudioTrack(
            id=r["id"],
            title=r["title"],
            artist=r["artist"],
            danceability=float(r.get("danceability", 0.5)),
            energy=float(r.get("energy", 0.5)),
            valence=float(r.get("valence", 0.5)),
            tempo=float(r.get("tempo", 120.0)),
            acousticness=float(r.get("acousticness", 0.2)),
            key=r.get("key"),
            mode=r.get("mode"),
            extras={"isrc": r.get("isrc"), "album": r.get("album"), "platform": r.get("platform")},
        )
        for r in rows
    ]
